apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: activemq
  name: activemq
spec:
  ports:
  - name: 61616-61616
    # Port exposed by the underlying pod
    port: 61616
    protocol: TCP
    # Port exposed by this service, such that traffics to targetPort will be directed to port exposed by the pod
    targetPort: 61616
  selector:
    app: activemq
  type: ClusterIP
status:
  loadBalancer: {}
