apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: activemq
  name: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: activemq
    spec:
      containers:
      - image: rmohr/activemq
        name: activemq
        # Purely informational
        ports:
        - containerPort: 61616
        - containerPort: 8161
        readinessProbe:
          httpGet:
            path: /
            port: 8161
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          requests:
            memory: "500Mi"
            cpu: "100m"
          limits:
            memory: "600Mi"
            cpu: "300m"
status: {}
