apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kafka0
  name: kafka0
spec:
  ports:
  - name: 9092-9092
    # Port exposed by the underlying pod
    port: 9092
    protocol: TCP
    # Port exposed by this service, such that traffics to targetPort will be directed to port exposed by the pod
    targetPort: 9092
  - name: 9093-9093
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    app: kafka0
  type: ClusterIP
status:
  loadBalancer: {}
