apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
      - image: trade_capture-mysql
        imagePullPolicy: Never
        name: trade-capture-mysql-9lf9v
        # Purely informational
        ports:
        - containerPort: 3306
        readinessProbe:
          exec:
            command:
              - mysqladmin
              - ping
              - -h
              - 127.0.0.1
              - -u
              - root
              - -p=root
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          requests:
            memory: "350Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "300m"
status: {}
