apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgres
  name: postgres
spec:
  ports:
  - name: 5432-5432
    # Port exposed by the underlying pod
    port: 5432
    protocol: TCP
    # Port exposed by this service, such that traffics to targetPort will be directed to port exposed by the pod
    targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
status:
  loadBalancer: {}
