apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: view-service
  name: view-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: view-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: view-service
    spec:
      containers:
      - image: trade_capture-view-service
        imagePullPolicy: Never
        name: trade-capture-view-service-j286v
        # Purely informational
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/trade_capture
        - name: SPRING_DATASOURCE_USERNAME
          value: mysu
        - name: SPRING_DATASOURCE_PASSWORD
          value: mypassword
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "300m"
status: {}
